# Base image
FROM python:3.11-slim

# Difine work folder
WORKDIR /app

# Install dependencies from requirements.txt
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run with uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
